from __future__ import annotations

import base64
from typing import List

from .models import ProhibitedProcess, ProxyConfig, SEBServerConfig
from .processes import build_prohibited_processes


class SEBConfig:
    """
    Instantiate, optionally override fields, then call build_plist_dict()
    to get the raw dict ready for plistlib serialisation.
    """

    def __init__(self) -> None:
        self.start_url = "https://www.codechef.com/"
        self.quit_url = "https://www.codechef.com/ide"
        self.duration_minutes: int | None = None
        self.originator_version = "SEB_iOS_3.5.4_15683"
        # sha256("admin123")
        self.hashed_admin_password = (
            "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9"
        )
        self.hashed_quit_password = ""
        self.exam_key_salt: bytes = base64.b64decode(
            "eT61mLw/OUZeBVst5ekv2alSZPBTFrdIE7o4w2mnlD0="
        )
        self.config_key_salt: bytes = b""

        self.proxy = ProxyConfig()
        self.seb_server = SEBServerConfig()
        self.prohibited_processes: List[ProhibitedProcess] = (
            build_prohibited_processes()
        )

    def build_plist_dict(self) -> dict:
        """Assemble the complete plist dictionary."""
        d = {
            # Custom CodeChef fields
            "examDurationMinutes": self.duration_minutes if self.duration_minutes is not None else 0,
            # URL filter
            "URLFilterEnable": False,
            "URLFilterEnableContentFilter": False,
            "URLFilterIgnoreList": [],
            "URLFilterMessage": 0,
            "URLFilterRules": [],
            # Accessibility / AAC
            "aacDnsPrePinning": False,
            "accessibilityFeatureAssistiveTouch": 0,
            "accessibilityFeatureGrayscaleDisplay": 0,
            "accessibilityFeatureInvertColors": 0,
            "accessibilityFeatureVoiceOver": 0,
            "accessibilityFeatureZoom": 0,
            "additionalResources": [],
            # Allow flags
            "allowAccessibilityVoiceOver": True,
            "allowApplicationLog": False,
            "allowAudioCapture": False,
            "allowBrowsingBackForward": False,
            "allowCustomDownUploadLocation": False,
            "allowDeveloperConsole": False,
            "allowDictation": False,
            "allowDictionaryLookup": False,
            "allowDisplayMirroring": False,
            "allowDownUploads": True,
            "allowDownloads": True,
            "allowFind": True,
            "allowFlashFullscreen": False,
            "allowMacOSVersionNumberCheckFull": False,
            "allowMacOSVersionNumberMajor": 11,
            "allowMacOSVersionNumberMinor": 0,
            "allowMacOSVersionNumberPatch": 0,
            "allowOpenAndSavePanel": False,
            "allowPDFPlugIn": False,
            "allowPDFReaderToolbar": False,
            "allowPreferencesWindow": True,
            "allowPrint": False,
            "allowQuit": True,
            "allowScreenCapture": False,
            "allowScreenSharing": False,
            "allowShareSheet": False,
            "allowSiri": False,
            "allowSpellCheck": False,
            "allowSwitchToApplications": False,
            "allowUploads": False,
            "allowUploadsiOS": False,
            "allowUserAppFolderInstall": False,
            "allowUserSwitching": True,
            "allowVideoCapture": False,
            "allowVirtualMachine": False,
            "allowWindowCapture": False,
            "allowWlan": True,
            "allowedDisplayBuiltin": False,
            "allowedDisplayBuiltinEnforce": False,
            "allowedDisplayBuiltinExceptDesktop": True,
            "allowedDisplaysIgnoreFailure": False,
            "allowedDisplaysMaxNumber": 1,
            "allowiOSBetaVersionNumber": 26,
            "allowiOSVersionNumberMajor": 13,
            "allowiOSVersionNumberMinor": 0,
            "allowiOSVersionNumberPatch": 0,
            # Audio
            "audioControlEnabled": True,
            "audioMute": False,
            "audioSetVolumeLevel": False,
            "audioVolumeLevel": 25,
            # Auto / Background
            "autoQuitApplications": True,
            "backgroundOpenSEBConfig": False,
            # Battery
            "batteryChargeThresholdCritical": 0.1,
            "batteryChargeThresholdLow": 0.2,
            # Browser
            "blacklistURLFilter": "",
            "blockPopUpWindows": False,
            "blockScreenShotsLegacy": False,
            "browserConnectionErrorReload": False,
            "browserMediaAutoplay": True,
            "browserMediaAutoplayAudio": True,
            "browserMediaAutoplayVideo": True,
            "browserMediaCaptureCamera": False,
            "browserMediaCaptureMicrophone": False,
            "browserMediaCaptureScreen": False,
            "browserMessagingPingTime": 120000,
            "browserMessagingSocket": "ws://localhost:8706",
            "browserScreenKeyboard": False,
            "browserShowFileSystemElementPath": True,
            "browserURLSalt": True,
            "browserUserAgent": "SEB",
            "browserUserAgentMac": 0,
            "browserUserAgentMacCustom": "",
            "browserUserAgentWinDesktopMode": 0,
            "browserUserAgentWinDesktopModeCustom": "",
            "browserUserAgentWinTouchMode": 0,
            "browserUserAgentWinTouchModeCustom": "",
            "browserUserAgentWinTouchModeIPad": (
                "Mozilla/5.0 (iPad; CPU OS 18_3 like Mac OS X) "
                "AppleWebKit/605.1.15 (KHTML, like Gecko) "
                "Version/18.3 Mobile/15E148 Safari/605.1.15"
            ),
            "browserUserAgentiOS": 0,
            "browserUserAgentiOSCustom": "",
            "browserViewMode": 1,
            "browserWindowAllowAddressBar": False,
            "browserWindowAllowReload": True,
            "browserWindowShowURL": 0,
            "browserWindowTitleSuffix": "",
            "browserWindowWebView": 2,
            "browserWindowWebViewClassicHideDeprecationNote": False,
            # Choose / Clipboard
            "chooseFileToUploadPolicy": 0,
            "clipboardPolicy": 2,
            # Config / Create
            "configFileCreateIdentity": False,
            "configFileEncryptUsingIdentity": False,
            "configKeySalt": self.config_key_salt,
            "createNewDesktop": True,
            # Default / Detect / Disable / Display / Download
            "defaultPageZoomLevel": 1.0,
            "defaultTextZoomLevel": 1.0,
            "detectStoppedProcess": True,
            "disableSessionChangeLockScreen": False,
            "displayAlwaysOn": True,
            "downloadAndOpenSebConfig": True,
            "downloadDirectoryOSX": "~/Downloads",
            "downloadDirectoryWin": "Downloads",
            "downloadFileTypes": [],
            "downloadPDFFiles": False,
            "embeddedCertificates": [],
            # Enable flags
            "enableAltEsc": False,
            "enableAltF4": False,
            "enableAltMouseWheel": False,
            "enableAltTab": True,
            "enableAppSwitcherCheck": True,
            "enableBrowserWindowToolbar": False,
            "enableChromeNotifications": False,
            "enableCtrlEsc": False,
            "enableCursorVerification": True,
            "enableDrawingEditor": False,
            "enableEsc": True,
            "enableF1": True,
            "enableF10": True,
            "enableF11": True,
            "enableF12": True,
            "enableF2": True,
            "enableF3": True,
            "enableF4": True,
            "enableF5": True,
            "enableF6": True,
            "enableF7": True,
            "enableF8": True,
            "enableF9": True,
            "enableFindPrinter": False,
            "enableJava": False,
            "enableJavaScript": True,
            "enableLogging": True,
            "enableMacOSAAC": True,
            "enableMiddleMouse": False,
            "enablePlugIns": True,
            "enablePrintScreen": False,
            "enablePrivateClipboard": True,
            "enablePrivateClipboardMacEnforce": True,
            "enableRightMouse": True,
            "enableRightMouseMac": False,
            "enableScreenProctoring": False,
            "enableScrollLock": True,
            "enableSebBrowser": True,
            "enableStartMenu": False,
            "enableTouchExit": False,
            "enableURLContentFilter": False,
            "enableURLFilter": False,
            "enableWindowsUpdate": False,
            "enableZoomPage": True,
            "enableZoomText": False,
            # Exam
            "examKeySalt": self.exam_key_salt,
            "examSessionClearCookiesOnEnd": True,
            "examSessionClearCookiesOnStart": True,
            "examSessionReconfigureAllow": False,
            "examSessionReconfigureConfigURL": "",
            # Exit keys
            "exitKey1": 2,
            "exitKey2": 10,
            "exitKey3": 5,
            "forceAppFolderInstall": True,
            # Passwords
            "hashedAdminPassword": self.hashed_admin_password,
            "hashedQuitPassword": self.hashed_quit_password,
            "hideBrowserWindowToolbar": False,
            "hookKeys": True,
            "ignoreExitKeys": True,
            "ignoreQuitPassword": False,
            # Inside SEB (Windows Ctrl+Alt+Del menu)
            "insideSebEnableChangeAPassword": False,
            "insideSebEnableEaseOfAccess": False,
            "insideSebEnableLockThisComputer": False,
            "insideSebEnableLogOff": False,
            "insideSebEnableNetworkConnectionSelector": False,
            "insideSebEnableShutDown": False,
            "insideSebEnableStartTaskManager": False,
            "insideSebEnableSwitchUser": False,
            "insideSebEnableVmWareClientShade": False,
            # Jitsi Meet
            "jitsiMeetAudioMuted": False,
            "jitsiMeetAudioOnly": False,
            "jitsiMeetEnable": False,
            "jitsiMeetFeatureFlagChat": False,
            "jitsiMeetFeatureFlagCloseCaptions": False,
            "jitsiMeetFeatureFlagDisplayMeetingName": False,
            "jitsiMeetFeatureFlagRaiseHand": False,
            "jitsiMeetFeatureFlagRecording": False,
            "jitsiMeetFeatureFlagTileView": False,
            "jitsiMeetReceiveAudio": False,
            "jitsiMeetReceiveVideo": False,
            "jitsiMeetRoom": "",
            "jitsiMeetSendAudio": True,
            "jitsiMeetSendVideo": True,
            "jitsiMeetServerURL": "",
            "jitsiMeetSubject": "",
            "jitsiMeetToken": "",
            "jitsiMeetUserInfoAvatarURL": "",
            "jitsiMeetUserInfoDisplayName": "",
            "jitsiMeetUserInfoEMail": "",
            "jitsiMeetVideoMuted": False,
            # Kill / Lock / Log
            "killExplorerShell": False,
            "lockOnMessageSocketClose": True,
            "logDirectoryOSX": "",
            "logDirectoryWin": "",
            "logLevel": 3,
            "logSendingRequiresAdminPassword": False,
            # Main browser window
            "mainBrowserWindowHeight": "100%",
            "mainBrowserWindowPositioning": 1,
            "mainBrowserWindowWidth": "100%",
            "minMacOSVersion": 9,
            # Mobile
            "mobileAllowInlineMediaPlayback": True,
            "mobileAllowPictureInPictureMediaPlayback": False,
            "mobileAllowQRCodeConfig": False,
            "mobileAllowSingleAppMode": False,
            "mobileCompactAllowInlineMediaPlayback": False,
            "mobileEnableASAM": True,
            "mobileEnableGuidedAccessLinkTransform": False,
            "mobileEnableModernAAC": False,
            "mobilePreventAutoLock": True,
            "mobileShowEditConfigShortcutItem": True,
            "mobileShowSettings": False,
            "mobileSleepModeLockScreen": True,
            "mobileStatusBarAppearance": 1,
            "mobileStatusBarAppearanceExtended": 1,
            "mobileSupportedFormFactorsCompact": True,
            "mobileSupportedFormFactorsNonTelephonyCompact": True,
            "mobileSupportedFormFactorsRegular": True,
            "mobileSupportedScreenOrientationsCompactLandscapeLeft": True,
            "mobileSupportedScreenOrientationsCompactLandscapeRight": True,
            "mobileSupportedScreenOrientationsCompactPortrait": True,
            "mobileSupportedScreenOrientationsCompactPortraitUpsideDown": False,
            "mobileSupportedScreenOrientationsRegularLandscapeLeft": True,
            "mobileSupportedScreenOrientationsRegularLandscapeRight": True,
            "mobileSupportedScreenOrientationsRegularPortrait": True,
            "mobileSupportedScreenOrientationsRegularPortraitUpsideDown": True,
            "monitorProcesses": True,
            # New browser window
            "newBrowserWindowAllowAddressBar": False,
            "newBrowserWindowAllowReload": True,
            "newBrowserWindowByLinkBlockForeign": False,
            "newBrowserWindowByLinkHeight": "100%",
            "newBrowserWindowByLinkPolicy": 0,
            "newBrowserWindowByLinkPositioning": 2,
            "newBrowserWindowByLinkWidth": "1000",
            "newBrowserWindowByScriptBlockForeign": False,
            "newBrowserWindowByScriptPolicy": 2,
            "newBrowserWindowNavigation": False,
            "newBrowserWindowShowReloadWarning": False,
            "newBrowserWindowShowURL": 0,
            "openDownloads": False,
            "originatorVersion": self.originator_version,
            "oskBehavior": 2,
            "permittedProcesses": [],
            "pinEmbeddedCertificates": False,
            # Proctoring AI
            "proctoringAIEnable": False,
            "proctoringDetectFaceAngleDisplay": True,
            "proctoringDetectFaceCount": True,
            "proctoringDetectFaceCountDisplay": True,
            "proctoringDetectFacePitch": True,
            "proctoringDetectFaceYaw": True,
            "proctoringDetectTalking": True,
            "proctoringDetectTalkingDisplay": True,
            # Prohibited processes
            "prohibitedProcesses": [p.to_dict() for p in self.prohibited_processes],
            # Proxy
            "proxies": self.proxy.to_dict(),
            "proxySettingsPolicy": 0,
            # Quit
            "quitURL": self.quit_url,
            "quitURLConfirm": True,
            "quitURLRestart": False,
            "raiseHandButtonAlwaysPromptMessage": False,
            "raiseHandButtonShow": True,
            "remoteProctoringViewShow": 0,
            "removeBrowserProfile": True,
            "removeLocalStorage": False,
            "restartExamPasswordProtected": False,
            "restartExamText": "",
            "restartExamURL": "",
            "restartExamUseStartURL": True,
            # Screen proctoring
            "screenProctoringCacheSize": 500,
            "screenProctoringClientId": "",
            "screenProctoringClientSecret": "",
            "screenProctoringClientSessionId": "",
            "screenProctoringGroupId": "",
            "screenProctoringImageDownscale": 1.0,
            "screenProctoringImageFormat": 0,
            "screenProctoringImageQuantization": 0,
            "screenProctoringIndicateHealthAndCaching": False,
            "screenProctoringMetadataActiveAppEnabled": True,
            "screenProctoringMetadataURLEnabled": True,
            "screenProctoringMetadataWindowTitleEnabled": True,
            "screenProctoringScreenshotMaxInterval": 5000,
            "screenProctoringScreenshotMinInterval": 1000,
            "screenProctoringServiceURL": "",
            "screenSharingMacEnforceBlocked": False,
            # SEB mode / server
            "sebConfigPurpose": 0,
            "sebMode": 0,
            "sebServerConfiguration": self.seb_server.to_dict(),
            "sebServerFallback": False,
            "sebServerFallbackAttemptInterval": 2000,
            "sebServerFallbackAttempts": 5,
            "sebServerFallbackPasswordHash": "",
            "sebServerFallbackTimeout": 30000,
            "sebServerURL": "",
            "sebServiceIgnore": True,
            "sebServicePolicy": 1,
            "sendBrowserExamKey": False,
            "setVmwareConfiguration": False,
            # Show flags
            "showApplicationLogButton": False,
            "showBackToStartButton": True,
            "showInputLanguage": True,
            "showMenuBar": True,
            "showNavigationButtons": False,
            "showProctoringViewButton": True,
            "showQuitButton": True,
            "showReloadButton": True,
            "showReloadWarning": True,
            "showScanQRCodeButton": False,
            "showScrollLockButton": True,
            "showSideMenu": True,
            "showTaskBar": True,
            "showTime": True,
            # Start URL
            "startResource": "",
            "startURL": self.start_url,
            "startURLAllowDeepLink": False,
            "startURLAppendQueryParameter": False,
            "systemAlwaysOn": False,
            "tabFocusesLinks": True,
            "taskBarHeight": 40,
            "terminateProcesses": False,
            "touchOptimized": False,
            "urlFilterRegex": False,
            "urlFilterTrustedContent": True,
            "useAsymmetricOnlyEncryption": False,
            "useTemporaryDownUploadDirectory": False,
            "whitelistURLFilter": "",
            # Zoom (legacy integration)
            "zoomAPIKey": "",
            "zoomAudioMuted": False,
            "zoomEnable": False,
            "zoomFeatureFlagChat": False,
            "zoomFeatureFlagCloseCaptions": False,
            "zoomFeatureFlagRaiseHand": False,
            "zoomFeatureFlagTileView": False,
            "zoomMeetingKey": "",
            "zoomMode": 0,
            "zoomReceiveAudio": False,
            "zoomReceiveVideo": False,
            "zoomRoom": "",
            "zoomSDKToken": "",
            "zoomSendAudio": True,
            "zoomSendVideo": True,
            "zoomServerURL": "",
            "zoomSubject": "",
            "zoomToken": "",
            "zoomUserInfoDisplayName": "",
            "zoomUserName": "",
            "zoomVideoMuted": False,
        }
        return d
